{"name": "test_login_with_valid_credentials", "status": "passed", "description": "Validate user login with valid credentials", "attachments": [{"name": "log", "source": "527eba49-3ed1-43bb-90bf-423fa44b2925-attachment.txt", "type": "text/plain"}], "start": 1718351375487, "stop": 1718351391439, "uuid": "0d7c1839-2693-4433-8777-cd48936f2f70", "historyId": "e4656aba8c0c474450644a2a1ad6ec60", "testCaseId": "e4656aba8c0c474450644a2a1ad6ec60", "fullName": "tests.test_login_001.TestLogin_001#test_login_with_valid_credentials", "labels": [{"name": "severity", "value": "NORMAL"}, {"name": "tag", "value": "sanity_Test_1"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_001"}, {"name": "subSuite", "value": "TestLogin_001"}, {"name": "host", "value": "DESKTOP-5K904R3"}, {"name": "thread", "value": "38724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_001"}]}